local_backend: true

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  site_domain: "https://berbat-photos.netlify.app"
  identity_url: "https://berbat-photos.netlify.app/.netlify/identity"

publish_mode: editorial_workflow

media_folder: "src/cms/general-images"
public_folder: "src/cms/general-images"

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, fr]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en


collections:
  - name: "homePage"
    label: "Home Page"
    folder: "src/cms/homepageContent"
    create: true
    slug: "{{slug}}"
    structure: single_file
    locales: [en, fr]
    preview_path: preview/{{slug}}
    fields:
    - name: 'header'
      lavbel: 'Header Content'
      widget: 'object'
      i18n: true
      fields:
        - { label: "Title", name: "title", widget: "string", i18n: true }
        - { label: "Subtitle", name: "subtitle", widget: "string", i18n: true }
        - { label: "Image", name: "image", widget: "image", media_folder: "src/cms/homepageContent", public_folder: "src/cms/homepageContent" }
